#!/bin/bash
# Installs all you need to start with RIOT-os on Ubuntu
# ubuntu packages, arm compiler and riot-os
# for this reason it will use sudo - to install packages
# it can also download RIOT (into current dir so you may have to move it up to ~/RIOT for an easy life)
# Kirk Martinez June 2020/22
# ubuntu 20 only has python3 - affects python3-serial and python3-pip
# needs sudo to install packages and config files
#sudo apt install python3-serial git build-essential python3-pip
#sudo apt install pkg-config autoconf automake libtool libusb-dev libusb-1.0-0-dev libhidapi-dev libftdi-dev libudev-dev
sudo apt install git gcc-arm-none-eabi make gcc-multilib libstdc++-arm-none-eabi-newlib openocd gdb-multiarch doxygen wget unzip python3-serial

if [ -e RIOT ] ; then
	echo "you already have a RIOT dir here"
else
	echo "getting RIOT-OS from github"
	git clone https://github.com/RIOT-OS/RIOT.git
fi

grep dialout < /etc/group | grep $USER
if [[ $? == 0 ]]; then
	echo "already in dialout group "
else
	echo "adding user to dialout group for access to /dev/tty.."
	sudo usermod --append --groups dialout $USER
	echo "YOU WILL HAVE TO LOG OUT AND BACK IN AGAIN afterwards"
fi

echo "checking for udev rule"
if [ ! -f /etc/udev/rules.d/99-usb.rules ] ; then
	echo "adding udev rule file /etc/udev/rules.d/99-usb.rules"
	echo "KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0664", GROUP="plugdev"" | sudo tee --append /etc/udev/rules.d/99-usb.rules

	sudo service udev restart
fi



